### ISSUE TITLE
Extension broken, fails to import from Utils

### ISSUE THREAD

**Issue by LennyN95** [MHubAI/SlicerMRunner#1]
The extension fails upon start with the following error message:

```
Traceback (most recent call last):
  File "/Applications/Slicer.app/Contents/Extensions-31938/SlicerMRunner/lib/Slicer-5.4/qt-scripted-modules/MRunner.py", line 110, in setup
    self.onUpdateRepoButtonClick(reinstallSegDB=False)
  File "/Applications/Slicer.app/Contents/Extensions-31938/SlicerMRunner/lib/Slicer-5.4/qt-scripted-modules/MRunner.py", line 441, in onUpdateRepoButtonClick
    from Utils import Models
ModuleNotFoundError: No module named 'Utils'
```

Likely, additional Python scripts or the containing folder needs to be referenced somehow, e.g., via the CMake file.

**Comment by LennyN95** [comment]
As supposed, the Utils and Dockerfiles folder where missing in the MRunner module, causing the mentioned error and another error when trying to download the model repo.

These resources are now included in the CMakeList updated in commit 74b32f16f6b75f81ecdd99d33f118823cb856f12.

The next nightly build will show if this works.
